// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5v902F8zqnylHimXFTfNjLLTIIj_AIpU',
    appId: '1:862796959604:web:7ca5f6ef5140441f39e621',
    messagingSenderId: '862796959604',
    projectId: 'reserveit-d950e',
    authDomain: 'reserveit-d950e.firebaseapp.com',
    storageBucket: 'reserveit-d950e.firebasestorage.app',
    measurementId: 'G-GP54YGZHZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2yaJoQHHkCzUdVfPHP05Vw_Q6jEHp0ws',
    appId: '1:862796959604:android:f31395f0b4ef186d39e621',
    messagingSenderId: '862796959604',
    projectId: 'reserveit-d950e',
    storageBucket: 'reserveit-d950e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYaXe-inIFL9ZQL2equNlMqpeKb2ApgJ8',
    appId: '1:862796959604:ios:3d178c087225750b39e621',
    messagingSenderId: '862796959604',
    projectId: 'reserveit-d950e',
    storageBucket: 'reserveit-d950e.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYaXe-inIFL9ZQL2equNlMqpeKb2ApgJ8',
    appId: '1:862796959604:ios:3d178c087225750b39e621',
    messagingSenderId: '862796959604',
    projectId: 'reserveit-d950e',
    storageBucket: 'reserveit-d950e.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5v902F8zqnylHimXFTfNjLLTIIj_AIpU',
    appId: '1:862796959604:web:05abc6d51009b35739e621',
    messagingSenderId: '862796959604',
    projectId: 'reserveit-d950e',
    authDomain: 'reserveit-d950e.firebaseapp.com',
    storageBucket: 'reserveit-d950e.firebasestorage.app',
    measurementId: 'G-CSLMP1HXTF',
  );
}
